apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: hadoop
    component: hdfs-dn
  name: hdfs-dn
  namespace: default
spec:
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: hadoop
      component: hdfs-dn
  serviceName: hdfs-dn
  template:
    metadata:
      labels:
        app: hadoop
        component: hdfs-dn
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: hadoop
                  component: hdfs-dn
              topologyKey: kubernetes.io/hostname
            weight: 5
      containers:
      - command:
        - /bin/bash
        - /tmp/hadoop-config/bootstrap.sh
        - -d
        image: danisla/hadoop:2.9.0
        imagePullPolicy: IfNotPresent
        name: hdfs-dn
#        livenessProbe:
#          failureThreshold: 3
#          httpGet:
#            path: /
#            port: 50075
#            scheme: HTTP
#          initialDelaySeconds: 10
#          periodSeconds: 10
#          successThreshold: 1
#          timeoutSeconds: 2
#        readinessProbe:
#          failureThreshold: 3
#          httpGet:
#            path: /
#            port: 50075
#            scheme: HTTP
#          initialDelaySeconds: 5
#          periodSeconds: 10
#          successThreshold: 1
#          timeoutSeconds: 2
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: 10m
            memory: 256Mi
        volumeMounts:
        - mountPath: /tmp/hadoop-config
          name: hadoop-config
        - mountPath: /root/hdfs/datanode
          name: dfs
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      volumes:
      - configMap:
          defaultMode: 420
          name: hadoop
        name: hadoop-config
      - emptyDir: {}
        name: dfs
  updateStrategy:
    type: OnDelete