apiVersion: v1
kind: Service
metadata:
  labels:
    component: spark-master
  name: master
  namespace: default
spec:
  ports:
  - port: 7077
    protocol: TCP
    targetPort: 7077
  selector:
    component: spark-master
  sessionAffinity: None
  type: ClusterIP