apiVersion: v1
kind: Service
metadata:
  labels:
    component: zeppelin
  name: zeppelin
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    nodePort: 32631
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    component: zeppelin
  sessionAffinity: None