apiVersion: v1
kind: Service
metadata:
  labels:
    app: hadoop
    component: hdfs-dn
  name: hdfs-dn
  namespace: default
spec:
  clusterIP: None
  ports:
  - name: dfs
    port: 9000
    protocol: TCP
    targetPort: 9000
  - name: webhdfs
    port: 50075
    protocol: TCP
    targetPort: 50075
  selector:
    app: hadoop
    component: hdfs-dn
  sessionAffinity: None
  type: ClusterIP