apiVersion: v1
kind: Service
metadata:
  labels:
    app: hadoop
    component: hdfs-nn
  name: hdfs-nn
  namespace: default
spec:
  clusterIP: None
  ports:
  - name: dfs
    port: 9000
    protocol: TCP
    targetPort: 9000
  - name: webhdfs
    port: 50070
    protocol: TCP
    targetPort: 50070
  selector:
    app: hadoop
    component: hdfs-nn
  sessionAffinity: None
  type: ClusterIP