apiVersion: v1
kind: Service
metadata:
  labels:
    app: hadoop
    component: yarn-nm
  name: yarn-nm
  namespace: default
spec:
  clusterIP: None
  ports:
  - name: web
    port: 8088
    protocol: TCP
    targetPort: 8088
  - name: web2
    port: 8082
    protocol: TCP
    targetPort: 8082
  - name: api
    port: 8042
    protocol: TCP
    targetPort: 8042
  selector:
    app: hadoop
    component: yarn-nm
  sessionAffinity: None
  type: ClusterIP