apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  labels:
    app: hadoop
    component: hdfs-nn
  name: hdfs-nn
  namespace: default
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: hadoop
      component: hdfs-nn